#ifndef MYSOFA_CONFIG_H
#define MYSOFA_CONFIG_H
#define CPACK_PACKAGE_VERSION_MAJOR 1
#define CPACK_PACKAGE_VERSION_MINOR 3
#define CPACK_PACKAGE_VERSION_PATCH 3
#define CMAKE_INSTALL_PREFIX ""
#endif
