#!/usr/bin/env python3
"""Derive a stable channel reorder map from compare_truehd_reference reports.

Input: one or more JSON reports generated by tools/compare_truehd_reference.py
Output:
- best ffmpeg->truehdd assignment (maximizing absolute correlation)
- inverse truehdd->ffmpeg map
- ffmpeg pan expression to reorder ffmpeg channels into truehdd order
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List, Tuple


def load_matrix(path: Path) -> List[List[float]]:
    obj = json.loads(path.read_text(encoding="utf-8"))
    m = obj.get("corr_matrix")
    if not isinstance(m, list) or not m:
        raise RuntimeError(f"{path}: missing corr_matrix")
    n = len(m)
    for row in m:
        if not isinstance(row, list) or len(row) != n:
            raise RuntimeError(f"{path}: non-square corr_matrix")
    return [[abs(float(v)) for v in row] for row in m]


def combine_matrices(mats: List[List[List[float]]]) -> List[List[float]]:
    n = len(mats[0])
    out = [[0.0] * n for _ in range(n)]
    for m in mats:
        for i in range(n):
            for j in range(n):
                out[i][j] += m[i][j]
    scale = 1.0 / max(len(mats), 1)
    for i in range(n):
        for j in range(n):
            out[i][j] *= scale
    return out


def solve_assignment_dp(score: List[List[float]]) -> Tuple[float, List[int]]:
    """Maximize sum(score[row][assigned_col]) with bitmask DP."""
    n = len(score)
    size = 1 << n
    dp = [-1.0e30] * size
    prev_mask = [-1] * size
    prev_col = [-1] * size
    dp[0] = 0.0

    for mask in range(size):
        row = mask.bit_count()
        if row >= n or dp[mask] < -1.0e20:
            continue
        for col in range(n):
            if mask & (1 << col):
                continue
            nm = mask | (1 << col)
            cand = dp[mask] + score[row][col]
            if cand > dp[nm]:
                dp[nm] = cand
                prev_mask[nm] = mask
                prev_col[nm] = col

    full = size - 1
    mapping = [-1] * n  # row(ffmpeg) -> col(truehdd)
    mask = full
    for row in range(n - 1, -1, -1):
        col = prev_col[mask]
        if col < 0:
            raise RuntimeError("assignment reconstruction failed")
        mapping[row] = col
        mask = prev_mask[mask]
    return dp[full], mapping


def invert_map(ffmpeg_to_truehdd: List[int]) -> List[int]:
    n = len(ffmpeg_to_truehdd)
    inv = [-1] * n
    for ff_ch, th_ch in enumerate(ffmpeg_to_truehdd):
        inv[th_ch] = ff_ch
    return inv


def pan_expr(truehdd_to_ffmpeg: List[int]) -> str:
    parts = []
    n = len(truehdd_to_ffmpeg)
    for out_ch in range(n):
        src = truehdd_to_ffmpeg[out_ch]
        if src < 0:
            src = 0
        parts.append(f"c{out_ch}=c{src}")
    return f"pan={n}c|" + "|".join(parts)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("reports", nargs="+", help="JSON reports from compare_truehd_reference.py")
    ap.add_argument("--json-out", default="")
    ap.add_argument("--confidence-threshold", type=float, default=0.8)
    args = ap.parse_args()

    paths = [Path(p) for p in args.reports]
    mats = [load_matrix(p) for p in paths]
    n = len(mats[0])
    if any(len(m) != n for m in mats):
        raise RuntimeError("all matrices must have same size")

    avg = combine_matrices(mats)
    total, ff_to_th = solve_assignment_dp(avg)
    th_to_ff = invert_map(ff_to_th)

    diag_scores = [avg[i][ff_to_th[i]] for i in range(n)]
    high_conf = [v >= args.confidence_threshold for v in diag_scores]
    result = {
        "reports": [str(p) for p in paths],
        "n_channels": n,
        "avg_abs_corr_assignment_sum": round(total, 6),
        "confidence_threshold": args.confidence_threshold,
        "ffmpeg_to_truehdd": ff_to_th,
        "truehdd_to_ffmpeg": th_to_ff,
        "per_ffmpeg_assigned_abs_corr": [round(v, 6) for v in diag_scores],
        "per_ffmpeg_high_confidence": high_conf,
        "high_confidence_ffmpeg_channels": [i for i, ok in enumerate(high_conf) if ok],
        "pan_reorder_ffmpeg_to_truehdd": pan_expr(th_to_ff),
    }

    text = json.dumps(result, indent=2)
    if args.json_out:
        Path(args.json_out).write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
